export const BUSCARTODOSCLIENTES = "getListClientsAll";
export const BUSCARCLIENTEPELOID = "getClientById";
export const EMPTYBUSCARCLIENTEPELOID = "emptyGetClientById";
export const CRIAROUALTERARCLIENTE = "alterOrCreateClient";
export const BUSCARLISTACLIENTERESUMIDA = "getClienAllResume";

export default {
  BUSCARTODOSCLIENTES,
  BUSCARCLIENTEPELOID,
  EMPTYBUSCARCLIENTEPELOID,
  CRIAROUALTERARCLIENTE,
  BUSCARLISTACLIENTERESUMIDA,
};
