export const BUSCARMARGEMPADRAO = "getMargin";
export const BUSCARTODOSPAGAMENTOSATIVOS = "getListPaymentsAll";
export const BUSCARPAGAMENTOPORID = "getPaymentById";
export const CRIAROUALTERARPAGAMENTO = "alterOrCreatePayment";
export const REMOVERPAGAMENTO = "removePayment";
//RECEBIMENTO
export const BUSCARTODOSRECEBIMENTOS = "getListReceiablesAll";
export const ALTERARRECEBIMENTO = "AlterarRecebimento";

export default {
  BUSCARMARGEMPADRAO,
  BUSCARTODOSPAGAMENTOSATIVOS,
  BUSCARPAGAMENTOPORID,
  CRIAROUALTERARPAGAMENTO,
  REMOVERPAGAMENTO,
  BUSCARTODOSRECEBIMENTOS,
  ALTERARRECEBIMENTO
};
