export const BUSCARTODOSOSPRODUTOS = "getListProductAll";
export const BUSCARPRODUTOPORID = "getProductById";
export const ALTERAROUCRIARPRODUTO = "alterOrCreateProduct";
export const EMPTYPRODUTO = "emptyProduto";
export const BUSCARPRODUTOSDISPONIVEISPARAVENDA = "getProductAllForSale";
export const BUSCARPRODUTOSPORFORNECEDORDISPONIVEISPARAVENDA = "getProductByPartnerForSale";

export default {
  BUSCARTODOSOSPRODUTOS,
  BUSCARPRODUTOPORID,
  ALTERAROUCRIARPRODUTO,
  EMPTYPRODUTO,
  BUSCARPRODUTOSDISPONIVEISPARAVENDA,
  BUSCARPRODUTOSPORFORNECEDORDISPONIVEISPARAVENDA
};
