export const BUSCARRELATORIOVENDAS = "getReportSales";
export const BUSCARRELATORIODEPAGAMENTOS = "getReportPayments";
export const BUSCARRELATORIOFLUXOCAIXA = "getAllSalesForCashFlow";
export const BUSCARRELATORIOCONTASARECEBER = "getReciavableAllReport";

export default {
  BUSCARRELATORIOVENDAS,
  BUSCARRELATORIODEPAGAMENTOS,
  BUSCARRELATORIOFLUXOCAIXA,
  BUSCARRELATORIOCONTASARECEBER
};
