export const BUSCARRELATORIOVENDAS = "getReportSales";
export const BUSCARRELATORIODEPAGAMENTOS = "getReportPayments";
export const BUSCARRELATORIOFLUXOCAIXA = "getAllSalesForCashFlow";

export default {
  BUSCARRELATORIOVENDAS,
  BUSCARRELATORIODEPAGAMENTOS,
  BUSCARRELATORIOFLUXOCAIXA
};
